server:
  port: 9090
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customers
          predicates:
            - Path=/customers/**
        - id: product-service
          uri: lb://products
          predicates:
            - Path=/products/**
        - id: order-service
          uri: lb://orders
          predicates:
            - Path=/orders/**
        - id: shopping-cart-command-service
          uri: lb://shopping-cart-command
          predicates:
            - Path=/shopping-cart-command/**
        - id: shopping-cart-query-service
          uri: lb://shopping-cart-query
          predicates:
            - Path=/shopping-cart-query/**
message: Hello from API Gateway
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

    //TODO: provide eureka server url
